### PR TITLE
migrating to WALA 1.4.0

### PR DESCRIPTION
**Pull request by mamarsh**
WALA 1.4.0 was just released, and there are some API changes.  Since we're using WALAFacade, I've made the changes in a local build.  It seems to work for my needs, but I don't know if everything is perfectly correct.

### CODE REVIEW

**Comment by cos** [comment]
This is great, thank you for contributing!

**Comment by mamarsh** [comment]
Do you have any timeline for cutting a new release?

**Comment by cos** [comment]
Cut a 0.2 release. Should be available from Maven Central in a few minutes.

**Comment by mamarsh** [comment]
Thanks!

**Pull request merged**
